### ISSUE TITLE
Can't get this to work with my Windows 10 PC

### ISSUE THREAD

**Issue by tnixa** [fx02/KodiLauncher#1]
I have a fresh install of Windows 10. I manually created the eHome directory since it  wasn't there and then I copied everything from the bin directory into the eHome. When I double click eshell.exe Kodi will launch but when I push the green start button on my MCE remote nothing happens.

**Comment by fx02** [comment]
Hi, is your remote properly detected? Please check device manager:
![image](https://user-images.githubusercontent.com/2067180/56425916-7c455800-62b6-11e9-8ee8-84c1ce40b8bb.png)

Also, check this [forum post](https://forum.kodi.tv/showthread.php?tid=164252) to properly map your buttons on remote. It worked for me out of the box on Windows 7, 8.1 and 10.

You can try to install WMC for Windows 10 to fix this but be careful as this might completely  crash your Windows 10 so i'm not responsible for any damage done by this packs:
https://mega.nz/#!7kdR1ICb!1TCdTd_UpqtYqVXyihhA6DwbFz1Yvo7fE8PVD21mrAU

or this one:
http://mega.nz/#!qegV2IgI!eqZBWXEEF6Lq7wSoNYcISM_6msgpXZITfYo677E4vWA

**Comment by fx02** [comment]
I remembered now how I fixed this as there is no Media Center on Windows 10. Disregard earlier post/suggestion.
- download remap tool: https://app.box.com/s/6zab0xg9k3n3wl09wtm7
- run it and remap GREEN key to: ALT + SHIFT + K or whatever suits you:
![image](https://user-images.githubusercontent.com/2067180/56429485-53778f80-62c3-11e9-82cf-bd852a1c1cf0.png)

Then click START > ALL PROGRAMS > KODI and right click on Kodi icon and add Shortcut key ALT + SHIFT + K:
![2019-04-19 16_53_21-Kodi Properties](https://user-images.githubusercontent.com/2067180/56429590-c1bc5200-62c3-11e9-8264-aa34dd91fca4.png)
- click Apply and OK
- test green key :)

**Comment by tnixa** [comment]
Thank you for the reply! Unfortunately it is still not working. I changed the green button to Ctrl-Atl-K and changed the Kodi shortcut and now when I do Ctrl-Atl-K on the keyboard Kodi launches but when I do the green button on the remote nothing happens (like before). I also tried mapping different remote buttons like '3' and '#' to Ctrl-Atl-K but that didn't help.

**Comment by fx02** [comment]
Hi, after remapping remote you need to save to registry and reboot Windows.

**Comment by tnixa** [comment]
Yeah, I did that. I think its an issue with my remote as its a VRC-1100 and not an OEM MCE remote.
